sudo: false

language: python

services:
  - docker

python:
  - "2.7"
  
jdk:
  - openjdk8

before_install:
  - docker build -t openbroker:openbroker .
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 openbroker:openbroker
  - docker ps -a

script:
  - git clone https://github.com/opendxl/opendxl-client-java.git
  - cd opendxl-client-java
  - ./gradlew assemble
  - java -jar ./build/libs/dxlclient*all.jar provisionconfig clientconfig 127.0.0.1 client -u admin -p password
  - sed -i -e "s/127.0.0.1;127.0.0.1/127.0.0.1/g" -e "/local/d" -e "/docker/d" clientconfig/dxlclient.config
  - cat clientconfig/dxlclient.config
  - ./gradlew test --info
